### ISSUE TITLE
Branches for different languages?

### ISSUE THREAD

**Issue by martinbean** [alejolp/grounded#1]
Interesting idea. One suggestion would be maybe have a branch per language? So your `master` may contain a README only, and then a `c` branch, a `python` branch, and so on.

**Comment by BeniaminK** [comment]
My first thought was: if you have every language in one branch, why do you make a different assets for each language? Why don't create just one assets folder shared between languages?

**Comment by alejolp** [comment]
I'd rather move all assets, maps and images, to a common folder. Thanks!
